version: '3'
services:
  php:
    build: ./docker/php/
    ports:
      - 80:80
    volumes:
      - ./brawlStars:/app
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: powerov1
      MYSQL_DATABASE: brawlStarts
      MYSQL_USER: juno
      MYSQL_PASSWORD: powerov1
    volumes:
      - ./docker/mysql/conf.d:/etc/mysql/conf.d
    ports:
      - 3306:3306
